name: S3 to GitHub Sync

on:
  schedule:
    - cron: '0 * * * *' # Runs once every hour
  workflow_dispatch: # Allows manual testing

permissions:
  contents: write 

jobs:
  sync-s3-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6 # Changed from v4
        with:
          fetch-depth: 1 

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6 # Changed from v4
        with:
          aws-access-key-id: AKIAVT6NRNAQ7II3ZLMG
          aws-secret-access-key: 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
          aws-region: us-east-1

      - name: Sync Data from S3
        run: |
          mkdir -p s3-data
          aws s3 sync s3://zappora-generated-code ./s3-data --exact-timestamps --exclude "*/node_modules/*" --exclude "*/.next/*" --exclude "*/dist/*" --exclude "*/build/*"
          

      - name: Check for Changes and Commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add ./s3-data
          
          if git diff --staged --quiet; then
            echo "No changes detected in S3. Skipping commit."
          else
            git commit -m "chore: auto-sync updates from S3 bucket"
            git push
            echo "Changes successfully committed and pushed to GitHub."
          fi
